### ISSUE TITLE
Error / crash on visiting Menu page

### ISSUE THREAD

**Issue by paulburgess** [Eworm/big-kahuna#37]
Hi - I have had Big Kahuna installed previously, deleted it, now reinstalled (after the page delete bug fix) - but I get an error when going to the menu page.

```
ErrorException in BigKahunaController.php line 37:
Undefined index: locale

in BigKahunaController.php line 37
at HandleExceptions->handleError('8', 'Undefined index: locale', '/Users/paulburgess/Websites/motive-v2/site/addons/BigKahuna/BigKahunaController.php', '37', array('request' => object(Request), 'menus_storage' =>... etc.
```

Screenshot: http://dlrg.co/fe151e572066

**Comment by Eworm** [comment]
The new version expects a locale, which the older version doesn't have. But you can add one to the storage file (the rest stayed the same). This is an example of the new setup:

```{
    "pages": [{
        "id": "93c5ea5e-581d-4074-af70-1eeae01d7880",
        "order": 1,
        "type": "Blog",
        "title": "My First Day",
        "original_title": "My First Day",
        "url": "http:\/\/statamic-kahuna.localhost\/blog\/2017\/01\/18\/my-first-day",
        "classname": "",
        "linktitle": "",
        "items": [],
        "pages": []
    }, {
        "id": "82f60ba2-6c16-4889-8420-d1c8e7adfa3d",
        "order": 2,
        "type": "Blog",
        "title": "Paperwork and Snowshoeing",
        "original_title": "Paperwork and Snowshoeing",
        "url": "http:\/\/statamic-kahuna.localhost\/blog\/2017\/01\/19\/paperwork-and-snowshoeing",
        "classname": "",
        "linktitle": "",
        "items": [],
        "pages": []
    }],
    "locale": "en"
}
```

**Comment by Eworm** [comment]
@paulburgess Did this help?

**Comment by paulburgess** [comment]
Yet to to try a fix - do you mean add:

```
"locale": "en"
```

to a file in the BigKahuna folder somewhere (still new to Statamic)

**Comment by Eworm** [comment]
Yes. The json file for the menu in site/storage/addons/BigKahuna. You should add the locale and change the json setup to the example above.

**Comment by thisJerem** [comment]
Hello Eworm !

I have a problem too with the locale option.
In dev mode, the locale is set automatically at the end of the file when saving BUT in production with same route file, when saving something in the menu the locale key is not added to JSON.
So I get the same error in production when clients are saving the menu...

I have only one locale 'fr' that is set by default, here is my routes.yaml : 
```
routes:
  /annonces:
    template: recherche
    withFilters: true
    load: /annonces
  '/annonces/{category}':
    template: recherche
    load: /annonces
    withFilters: true
  '/annonces/{category}/{discipline}':
    template: recherche
    load: /annonces
    withFilters: true
collections:
  annonce: '/{category}/{slug}'
  candidats: '/candidat/{slug}'
```
